[package]
name = "red-pegasus"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
winit = { version = "0.30", features = ["rwh_05"] }
env_logger = "0.11"
log = "0.4"
wgpu = "23.0"
pollster = "0.3"

#[[bin]]
#name = "red-pegasus"
#path = "src/main.rs"