[package]
name = "red-pegasus"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.14"
winit = "0.28"
egui = "0.21"
egui-winit = "0.21"
egui-wgpu = "0.21"
tokio = { version = "1", features = ["full"] }

